/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'com.google.cloud.artifactregistry.gradle-plugin' version '2.2.5' apply false
}

def isPublishing = gradle.startParameter.taskNames.any { it.endsWith('publish') || it.contains('ArtifactRegistry') }
if (isPublishing) {
    apply plugin: 'com.google.cloud.artifactregistry.gradle-plugin'
}

group = 'com.google.api-ads'
description = 'Utilities for working with the Data Manager API'
version = '0.4.0rc1'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        library(MavenPublication) {
            from components.java
            pom {
                name = 'Google Data Manager API Utilities'
                description = 'Utilities for working with the Data Manager API'
                url = 'https://github.com/googleads/data-manager-java'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'josh'
                        name = 'Josh Radcliff'
                        email = 'jradcliff@users.noreply.github.com'
                        organization = 'Google'
                        organizationUrl = 'https://www.google.com'
                    }
                    developer {
                        id = 'lindsey'
                        name = 'Lindsey Volta'
                        email = 'lindsey-volta@users.noreply.github.com'
                        organization = 'Google'
                        organizationUrl = 'https://www.google.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/googleads/data-manager-java.git'
                    developerConnection = 'scm:git:ssh://github.com:googleads/data-manager-java.git'
                    url = 'https://github.com/googleads/data-manager-java'
                }
            }
        }
    }
    repositories {
        if (isPublishing) {
            maven {
                name = 'ExitGateArtifactRegistry'
                url = uri(findProperty('artifact-registry-url') ?: "artifactregistry://us-maven.pkg.dev/oss-exit-gate-prod/measurement-devrel--mavencentral")
            }
        }
    }
}

signing {
    def signingKey = findProperty("signingKey") ?: System.getenv("SIGNING_KEY")
    def signingPassword = findProperty("signingPassword") ?: System.getenv("SIGNING_PASSWORD")
    if (signingKey) {
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign publishing.publications.library
    }
}

// Creates install "alias".
task install(dependsOn: publishToMavenLocal)

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    // Use Maven Local for the Data Manager library.
    mavenLocal()
}

dependencies {
    // Use JUnit test framework.
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.hamcrest:hamcrest:2.2'
    testImplementation 'org.mockito:mockito-core:5.17.0'

    implementation 'com.google.guava:guava:31.1-jre'
    implementation 'com.google.crypto.tink:tink:1.17.0'
    // Include the Google Cloud KMS extension for retrieving keys.
    implementation 'com.google.crypto.tink:tink-gcpkms:1.10.0'
}

